/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.diu6;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.opencv.core.Core;

/**
 *
 * @author TESTER
 */
public class Practica6 extends javax.swing.JFrame {

    /**
     * Creates new form Practica6
     */
    
    JFileChooser fc = new JFileChooser();
    Umbraliza umbraliza = new Umbraliza();
    private FileNameExtensionFilter fFilter;
    
    public Practica6() {
        //nu.pattern.OpenCV.loadShared();
        //System.loadLibrary(Core.NATIVE_LIBRARY_NAME);

        initComponents();
        this.fFilter = new FileNameExtensionFilter("Imagenes","png","jpg","jpeg");
        this.fc.addChoosableFileFilter(fFilter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        umbraliza2 = new com.mycompany.diu6.Umbraliza();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFicheros = new javax.swing.JMenu();
        abrir = new javax.swing.JMenuItem();
        editar = new javax.swing.JMenuItem();
        guardar = new javax.swing.JMenuItem();
        cerrar = new javax.swing.JMenuItem();
        ayuda = new javax.swing.JMenu();
        verAyuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        umbraliza2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout umbraliza2Layout = new javax.swing.GroupLayout(umbraliza2);
        umbraliza2.setLayout(umbraliza2Layout);
        umbraliza2Layout.setHorizontalGroup(
            umbraliza2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );
        umbraliza2Layout.setVerticalGroup(
            umbraliza2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );

        jLabel1.setText("Brian Palmés Gómez");

        menuFicheros.setText("Ficheros");

        abrir.setText("Abrir");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        menuFicheros.add(abrir);

        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        menuFicheros.add(editar);

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        menuFicheros.add(guardar);

        cerrar.setText("Cerrar");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        menuFicheros.add(cerrar);

        jMenuBar1.add(menuFicheros);

        ayuda.setText("Ayuda");

        verAyuda.setText("Ver");
        verAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verAyudaActionPerformed(evt);
            }
        });
        ayuda.add(verAyuda);

        jMenuBar1.add(ayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(umbraliza2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(umbraliza2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        // TODO add your handling code here:
         int res = fc.showOpenDialog(null);
         if(res == JFileChooser.APPROVE_OPTION){
            File f = this.fc.getSelectedFile();
            System.out.println(f);
        
            if(this.fFilter.accept(f)){
                try {
                    
                    this.umbraliza2.reloadCanvas(f);
                    
                    // Activammos opciones sobre el archivo
                    this.guardar.setEnabled(true);
                    this.editar.setEnabled(true);
                } catch (IOException ex) {
                    Logger.getLogger(Practica6.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Tipo de fichero erróneo", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_abrirActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        File outputFile = new File(this.umbraliza2.getCurrentPictureName() + "_modificado" + this.umbraliza.getCurrentPictureFormat());
        this.fc.setSelectedFile(outputFile);
        int jFileChooserOptionSelected = this.fc.showSaveDialog(this);
        try {
            
            if(jFileChooserOptionSelected == JFileChooser.APPROVE_OPTION){
            String fileToSave = this.fc.getCurrentDirectory() + "\\" + outputFile.getName();
            ImageIO.write(this.umbraliza2.getCurrentPicture(), "jpg", new File(fileToSave));
        }
        } catch (IOException ex) {
            Logger.getLogger(Practica6.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog("Inserte el factor de realce debe ser un entero");
        int parseInt = Integer.parseInt(input); //Por si acaso
            try {
                this.umbraliza2.umbralizacion(Integer.parseInt(input));
            } catch (IOException ex) {
                Logger.getLogger(Practica6.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_editarActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        // TODO add your handling code here:
       this.dispose();
    }//GEN-LAST:event_cerrarActionPerformed

    private void verAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verAyudaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, this.verAyuda(), "Ayuda", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_verAyudaActionPerformed
    
    public static String verAyuda(){
        return "Ayuda:\n"
                + "- Use la opcion Abrir del menu para abrir un archivo de su elección\n"
                + "-Use la opción editar para cambiar el factor de umbralización, podra introducir el numero entero que desee\n"
                + "- Use la opcion de Guardar para guardar sus cambios en el la imagen";       
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practica6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practica6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practica6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practica6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practica6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrir;
    private javax.swing.JMenu ayuda;
    private javax.swing.JMenuItem cerrar;
    private javax.swing.JMenuItem editar;
    private javax.swing.JMenuItem guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuFicheros;
    private com.mycompany.diu6.Umbraliza umbraliza2;
    private javax.swing.JMenuItem verAyuda;
    // End of variables declaration//GEN-END:variables
}
